base: 'http://cms24.s2310456017.student.kwmhgb.at/'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    locale: de_DE
    navigationTitle: Deutsch
    flag: de
    hreflang: ''
    websiteTitle: ''
rootPageId: 1
websiteTitle: 'Landwirtschaft verstehen'
